name: CI

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #CheckOut
      - name: Checkout repository
        uses: actions/checkout@v4

      #Node setup and build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Run unit tests
      - name: Run unit tests (Vitest)
        run: npm run test:ci

      # Build project
      - name: Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      #Setup python for robot tests
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      #Setup Robot Framework
      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      #Pull requests: run SMOKE only
      - name: Run Robot Smoke tests (PR)
        if: github.event_name == 'pull_request'
        env:
          BASE_URL: https://elmurmeli.github.io/Gym-App
        run: |
          robot \
            --include smoke \
            --variable BROWSER:headlesschrome \
            --outputdir robot-results \
            tests/

      #Push to main: run FULL suite
      - name: Run Robot Full Tests (main)
        if: github.event_name == 'push'
        env:
          BASE_URL: https://elmurmeli.github.io/Gym-App
        run: |
          robot \
            --variable BROWSER:headlesschrome \
            --outputdir robot-results \
            tests/

      #Upload test reports
      - name: Upload Robot reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: robot-results